name: Continuous Deployment

on:
  release:
    types: [edited,published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - run: IMAGE_TAG=${{ env.VERSION }} make docker/build
      - run: IMAGE_TAG=${{ env.VERSION }} make docker/push
      - run: IMAGE_TAG=latest make docker/push
